---
- hosts: all
  become: false
  tasks:
  
  - name: install packages in any OS
    ansible.builtin.package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}" 
      state: latest
      update_cache: yes  

      
