---
- hosts: all
  become: false
  tasks:
  
#  - name: update repository index
#    ansible.builtin.apt:
#      update_cache: yes
#    when: ansible_distribution == "Ubuntu"

  - name: install packages in Ubuntu
    ansible.builtin.apt:
      name:
        - apache2
        - libapache2-mod-php 
      state: latest
      update_cache: yes  
    when: ansible_distribution == "Ubuntu"   

  - name: install packages in Fedora
    ansible.builtin.dnf:
      name:
        - httpd
        - php  
      state: latest
      update_cache: yes  
    when: ansible_distribution == "Fedora"  
      
            
  #- name: install support for php
  #  ansible.builtin.apt:
  #    name: libapache2-mod-php
  #    state: latest    
      
